server:
  port: 9601
logging:
  level:
    cn.bootx.engine.shop: debug

spring:
  cloud:
    # 限流
    sentinel:
      transport:
        port: 19601
    stream:
      bindings:
        # 支付中心事件
        paymentCenterInput:
          destination: service-payment-center
          group: ${spring.application.name}
        paymentCenterOutput:
          destination: service-payment-center
        # 商品中心
        goodsCenterOutput:
          destination: service-goods-center
        # 订单中心
        orderCenterOutput:
          destination: service-order-center
        binders:
          local_rabbit:
            type: rabbit
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/service-shop-engine?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
    username: bootx
    password: password
  #redis
  redis:
    database: 1
    host: 127.0.0.1
    port: 26379
    password: password
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
seata:
  service:
    vgroup-mapping:
      service-shop-engine: default
  tx-service-group: service-shop-engine
bootx:
  starter:
    tenant:
      single: true
      tenant-id: 10011
    swagger:
      enabled: true
      base-package: cn.bootx.engine.shop
      version: 1.0
      title: 商城引擎
    snowflake:
      worker-id: 7
      datacenter-id: 1