metadata:
- appName: 网关
  dataId: bootx-gateway-dev.yml
  desc: 网关
  group: DEFAULT_GROUP
  type: yaml
- appName: 基础服务平台
  dataId: service-bsp-dev.yml
  desc: 基础服务平台
  group: DEFAULT_GROUP
  type: yaml
- appName: 基础api
  dataId: service-baseapi-dev.yml
  desc: 基础api
  group: DEFAULT_GROUP
  type: yaml
- appName: 用户中心
  dataId: service-user-center-dev.yml
  desc: 用户中心
  group: DEFAULT_GROUP
  type: yaml
- appName: 认证中心
  dataId: service-auth-center-dev.yml
  desc: 认证中心
  group: DEFAULT_GROUP
  type: yaml
- appName: 通知中心
  dataId: service-notice-center-dev.yml
  desc: 通知中心
  group: DEFAULT_GROUP
  type: yaml
- appName: 公共配置
  dataId: bootx-common-config-dev.yml
  desc: 公共配置
  group: DEFAULT_GROUP
  type: yaml
- appName: 销售中心
  dataId: service-sales-center-dev.yml
  desc: 销售中心
  group: DEFAULT_GROUP
  type: yaml
- appName: 商品中心
  dataId: service-goods-center-dev.yml
  desc: 商品中心
  group: DEFAULT_GROUP
  type: yaml
- appName: 商城引擎
  dataId: service-shop-engine-dev.yml
  desc: 商城引擎
  group: DEFAULT_GROUP
  type: yaml
- appName: 支付中心
  dataId: service-payment-center-dev.yml
  desc: 支付中心
  group: DEFAULT_GROUP
  type: yaml
- appName: 订单中心
  dataId: service-order-center-dev.yml
  desc: 订单中心
  group: DEFAULT_GROUP
  type: yaml
